### ISSUE TITLE
Documentation link redirects to slightly outdated documentation

### ISSUE THREAD

**Issue by hampelm** [tarbell-project/tarbell-site#3]
:tada: :birthday:  :tada: 

The "Documentation" link at tarbell.io points to `http://tarbell.readthedocs.org`. That page redirects to the 1.0 docs, which have a warning about a minor version bump: 

![screen shot 2015-06-25 at 4 35 00 pm](https://cloud.githubusercontent.com/assets/86435/8364986/2e69798a-1b58-11e5-9ffb-6b40f408f4b1.png)

Going manually to http://tarbell.readthedocs.org/en/latest/ works as expected. Not sure where the change would be (here or docs) so I wanted to post an issue instead of a PR.

**Comment by eads** [comment]
Fixed! Thanks for reporting this.

**Comment by eads** [comment]
As a sidenote, I should mention how I fixed it: There's a default branch setting on readthedocs that determines which branch "/" maps to that's different from /latest.
